ALTER TABLE patients
    ADD COLUMN IF NOT EXISTS blood_group VARCHAR(10) NULL,
    ADD COLUMN IF NOT EXISTS height DOUBLE NULL,
    ADD COLUMN IF NOT EXISTS weight DOUBLE NULL,
    ADD COLUMN IF NOT EXISTS profile_image_url VARCHAR(500) NULL;

